# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SEC_TS_Y771)	+= sec_ts/y771/
obj-$(CONFIG_TOUCHSCREEN_SEC_TS_Y771_D)	+= sec_ts/y771_d/
